create table client
(
    id            int8 generated by default as identity,
    client_name   varchar(255) not null,
    creation_date timestamp,
    subscriber_id int8,
    primary key (id)
);

create table subscriber
(
    id            int8 generated by default as identity,
    creation_date timestamp    not null,
    email         varchar(255) not null,
    password      varchar(255) not null,
    role          int4         not null,
    primary key (id)
);
create table ticket
(
    id            int8 generated by default as identity,
    date_creation timestamp not null,
    value         int8      not null,
    client        int8      not null,
    primary key (id)
);

alter table if exists subscriber
    add constraint subscriber_email_unique unique (email);

alter table if exists client
    add constraint client_subscriber_id_fk foreign key (subscriber_id) references subscriber;

alter table if exists ticket
    add constraint ticket_client_fk foreign key (client) references client;